export default [
    {
        id: 1,
        name: "Iphone 14 Plus",
        price: "5219.10",
        feedback: 4.8,
        photo: "/img/iphone_14.png",
        categoria: ["tecnologia", "smartphone"],
    },
    {
        id: 2,
        name: "Notebook Samsung Intel Core i3-1115g4 4GB",
        price: "2339.10",
        feedback: 4.9,
        photo: "/img/notebook.png",
        categoria: ["tecnologia"],
    },
    {
        id: 3,
        name: "Escada Alumínio Doméstica 5 Degraus",
        price: "120.80",
        feedback: 5,
        photo: "/img/escada.png",
        categoria: ["para casa"],
    },
    {
        id: 4,
        name: "Jogo de Panela Tramontina",
        price: "389.99",
        feedback: 4.5,
        photo: "/img/panela.png",
        categoria: ["cozinha"],
    },
    {
        id: 5,
        name: "Fritadeira Air Fry Philco",
        price: "679.05",
        feedback: 5,
        photo: "/img/air fry.jpg",
        categoria: ["cozinha", "eletrônico"],
    },
    {
        id: 6,
        name: "Console Playstation 5 825GB SSD",
        price: "4184.91",
        feedback: 5,
        photo: "/img/ps5.png",
        categoria: ["videogame", "tecnologia"],
    },
    {
        id: 7,
        name: "Headset Gamer HyperX",
        price: "129.90",
        feedback: 4.2,
        photo: "/img/fone.jpg",
        categoria: ["videogame", "tecnologia"],
    },
    {
        id: 8,
        name: "Smart TV 75' QLED 4K Samsung",
        price: "11399.05",
        feedback: 5,
        photo: "/img/tv.png",
        categoria: ["tecnologia", "televisão"],
    },
    {
        id: 9,
        name: "Cadeira de Escritório Presidente Giratória Preta",
        price: "303.70",
        feedback: 4.8,
        photo: "/img/cadeira.png",
        categoria: ["móvel"],
    },
    {
        id: 10,
        name: "Samsung Galaxy S20 FE 256GB",
        price: "1499.90",
        feedback: 4.8,
        photo: "/img/s20.png",
        categoria: ["smartphone", "tecnologia"],
    },
    {
        id: 11,
        name: "Câmera Inteligente Interna Wi-Fi Full HD",
        price: "404.01",
        feedback: 3.2,
        photo: "/img/camera.jpg",
        categoria: ["tecnologia"],
    },
    {
        id: 12,
        name: "Jogo de Taça de Cristal Para Vinho",
        price: "127.16",
        feedback: 4.6,
        photo: "/img/taca.png",
        categoria: ["cozinha"],
    },

]