export default [
    {
        id: 1,
        name: "Iphone 14 Plus 128GB",
        price: "5219.10",
        feedback: 4.8,
        photo: "/img/iphone_14.png",
        category: ["technology", "smartphone"],
    },
    {
        id: 2,
        name: "Notebook Samsung Intel Core i3-1115g4 4GB",
        price: "2339.10",
        feedback: 4.9,
        photo: "/img/notebook.png",
        category: ["technology"],
    },
    {
        id: 3,
        name: "Escada Alumínio Doméstica 5 Degraus",
        price: "120.80",
        feedback: 5,
        photo: "/img/escada.png",
        category: ["home products"],
    },
    {
        id: 4,
        name: "Jogo de Panela Tramontina",
        price: "389.99",
        feedback: 4.5,
        photo: "/img/panela.png",
        category: ["kitchen"],
    },
    {
        id: 5,
        name: "Fritadeira Air Fry Philco",
        price: "679.05",
        feedback: 5,
        photo: "/img/air fry.jpg",
        category: ["kitchen", "eletronic"],
    },
    {
        id: 6,
        name: "Console Playstation 5 825GB SSD",
        price: "4184.91",
        feedback: 5,
        photo: "/img/ps5.png",
        category: ["videogame", "technology"],
    },
    {
        id: 7,
        name: "Headset Gamer HyperX",
        price: "129.90",
        feedback: 4.2,
        photo: "/img/fone.jpg",
        category: ["videogame", "technology", "headset"],
    },
    {
        id: 8,
        name: "Smart TV 75' QLED 4K Samsung",
        price: "11399.05",
        feedback: 5,
        photo: "/img/tv.png",
        category: ["technology", "televison"],
    },
    {
        id: 9,
        name: "Cadeira de Escritório Presidente Giratória Preta",
        price: "303.70",
        feedback: 4.8,
        photo: "/img/cadeira.png",
        category: ["forniture"],
    },
    {
        id: 10,
        name: "Samsung Galaxy S20 FE 256GB",
        price: "1499.90",
        feedback: 4.8,
        photo: "/img/s20.png",
        category: ["smartphone", "technology"],
    },
    {
        id: 11,
        name: "Câmera Inteligente Interna Wi-Fi Full HD",
        price: "404.01",
        feedback: 3.2,
        photo: "/img/camera.jpg",
        category: ["technology"],
    },
    {
        id: 12,
        name: "Jogo de Taça de Cristal Para Vinho",
        price: "127.16",
        feedback: 4.6,
        photo: "/img/taca.png",
        category: ["kitchen"],
    },

]